### ISSUE TITLE
Make it into a UI 

### ISSUE THREAD

**Issue by realnovak** [Z3NTL3/ProxyBeast#8]
make it into a easy to access UI

**Comment by Z3NTL3** [comment]
Hi,

I have good news for you. We will add cross platform GUI surface to the tool. Of course this modification does not mean that the CLI version will be purged. 

We will simply cover two different versions, one which has a GUI and the other which is a CLI tool.

At the moment I am very busy with several business projects and my internship. I will start maintaining this once upon my free time.

After the deadline, I will simply re-comment under this improvement issue to have you in touch with the update.

**Comment by zaxhod** [comment]
alright 👍, can i have your discord by any chance?

**Comment by Z3NTL3** [comment]
> alright 👍, can i have your discord by any chance?

ofc, ``Z3NTL3#2036``

**Comment by Z3NTL3** [comment]
yo, bcs mingw does not work well with my windows i cannot develop in Fyne and for that reason i will break down my promise and say in sorry that this issue will not be completed.

however we have had a big update recently;
> In the previous version there were many bugs and socks4/socks5 check was dirty, with this new version we have enhanced these things and now it is precise and accurate in checking all protocols!
> https://www.youtube.com/watch?v=Me-kgUIcb84

**Comment by Z3NTL3** [comment]
Sup, again. I am revamping ProxyBeast completely, you can find out what's changing by reading the readme.

The reason for me to re-open this issue is for the reason that we're bringing ProxyBeast into an CLI, GUI and web interface all at once. Whether you'd like to scan proxies from Pix4's network, want to use our desktop or CLI app, all up to your choice!

![image](https://github.com/Z3NTL3/ProxyBeast/assets/48758770/0961923c-a521-45dc-a85b-8ec0ee9adb36)
